print("----------------------------------------")
print("Tugas 1 Sisop Kelas A")
print("----------------------------------------")
print("Nama : Fajri Uswatul Hanifah")
print("NPM  : 21083010058 ")
print("----------------------------------------")
print("Notes:")
print("----------------------------------------")
print("Halo dunia!")
print("Ini adalah skrip Python pertamaku di Linux")
